-- Esquema anterior à adoção do Flyway. Bancos novos executam esta migration.
-- Bancos existentes compatíveis devem receber baseline explícito na versão 1.
CREATE TABLE users (
    id UUID NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE establishment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    maps_url VARCHAR(1000),
    owner_id UUID NOT NULL,
    automatic_updates_enabled BOOLEAN,
    last_mining_at TIMESTAMP(6),
    last_mining_success_at TIMESTAMP(6),
    next_mining_at TIMESTAMP(6),
    last_new_reviews INTEGER,
    last_mining_status VARCHAR(255),
    last_mining_message VARCHAR(1000),
    CONSTRAINT pk_establishment PRIMARY KEY (id),
    CONSTRAINT fk_establishment_owner FOREIGN KEY (owner_id) REFERENCES users (id)
);

CREATE TABLE review (
    id VARCHAR(255) NOT NULL,
    author VARCHAR(255),
    text VARCHAR(5000),
    rating DOUBLE PRECISION,
    date VARCHAR(255),
    source VARCHAR(255),
    sentiment_score DOUBLE PRECISION,
    overall_sentiment VARCHAR(255),
    analysis_date VARCHAR(255),
    collected_at TIMESTAMP(6),
    establishment_id BIGINT,
    CONSTRAINT pk_review PRIMARY KEY (id),
    CONSTRAINT fk_review_establishment FOREIGN KEY (establishment_id) REFERENCES establishment (id)
);

CREATE TABLE aspect (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    sentiment VARCHAR(255),
    excerpt VARCHAR(1000),
    review_id VARCHAR(255),
    CONSTRAINT pk_aspect PRIMARY KEY (id),
    CONSTRAINT fk_aspect_review FOREIGN KEY (review_id) REFERENCES review (id)
);
